config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :scores
  root 'top#index'
  get "about/index" => "about#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/chord.rb
class Chord < ApplicationRecord
end

app/models/key.rb
class Key < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user

  validates :tittle, presence: true
  validates :user, presence: true


end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :scores
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    scores_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


protected
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
  # .order(id:"DESC")で最新の投稿を上に表示させる
    @scores = Score.all.order(id: "DESC")
    @user = User.find_by(params[:id])
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])
    @user = User.find_by(id: @score.user_id)
  end

  # GET /scores/new
  def new
    @score = Score.new

  end

  # GET /scores/1/edit
  def edit

  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.user = current_user
    user = User.find_by_id(params[:id])

    @current_user ||= User.find_by(id: session[:user_id])


    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:tittle, :key, :chord)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<%= render 'layouts/header' %>
<body>

<div class="jumbotron">
   <div class="container">
     <div class="text-center">
       <h1>About</h1>
       <h2>Analyとは</h2>
    </div>
   </div>
 </div>
</body>

app/views/layouts/_header.html.erb
<header>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
    <div class="col-md-12" style="margin:0 0 0 0;">

      <div class="center-block" style="margin: 0 0 25px 0;",color:#555;>
        <nav class="nav navbar-nav navbar-left" style="margin-right: 50px;">
          <%=link_to root_path, :style=>"color:#777;text-decoration: none;" do %>
          <h1>Analy</h1>
          <% end %>
        </nav>
      </div>


      <div id="slidemenu">
      </div>


          <ul class="nav navbar-nav navbar-center" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <li class="inline-block">
                <%=link_to about_index_path, :style=>"margin:0 0px 0 15px;" do%>
                <p>About</p>
                <% end %>
              </li>
              <li class="inline-block">
                <%=link_to scores_path, :style=>"margin:0 0px 0 15px;" do%>
                <p>スコア</p>
                <% end %>
              </li>

          </ul>
          <ul class="navbar-right" style="margin:15px 0px 0px 0px;">
              <% if user_signed_in? %>
              <%= current_user.name %>
                <%= link_to " log out", destroy_user_session_path, class: "glyphicon glyphicon-log-out navbar-link", style: "padding: 0 15px 0 15px;", method: :delete %>
              <% else %>
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up", style: "padding: 0 35px 0 13px;"  %>
                <%= link_to " log in", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in",  style: "padding: 0 15px 0 13px;"  %>
              <% end %>
          </ul>




    </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tittle %><br>
    <%= form.text_field :tittle %>
  </div>

  <div class="field">
    <%= form.label :key %><br>
    <%= form.select :key,[["C", "C"], ["C#/Db", "C#/Db"],["D", "D"], ["D#/Eb", "D#/Eb"],["E", "E"], ["F", "F"],["F#/Gb", "F#/Gb"], ["G", "G"], ["G#/Ab", "G#/Ab"],["A", "A"], ["A#/Bb", "A#/Bb"],["B", "B"]] %>
  </div>

  <div class="field">
    <%= form.label :chord %><br>
      <%= form.text_area :chord %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
  <div class="col-md-12">

<h1>スコア編集</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score, class: 'btn btn-default' %>
<%= link_to 'Back', scores_path, class: 'btn btn-default' %>

</div>
</div>
</div>

app/views/scores/index.html.erb
<%= render 'layouts/header' %>
<body>
  <div class="header-under">
  </div>
<div class="container">
  <div class="row">
  <div class="col-md-12">


<h1>スコア一覧</h1>
<div class="">
  <% if user_signed_in? %>
  <%= link_to 'New Score', new_score_path, class: 'btn btn-default' %>
  <% else %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <div class="box" style="margin:15px 0px 15px 0px;">
        <td><%= score.tittle %></td>
        <td><%= score.user.name %></td>
        <td><%= link_to 'Show', score, class: 'btn btn-default' %></td>        </div>
      </tr>
    <% end %>
  </tbody>
</table>



  </div>
  </div>
</div>
</body>

app/views/scores/new.html.erb
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
  <div class="col-md-12">
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path, class: 'btn btn-default' %>

  </div>
  </div>
</div>

app/views/scores/show.html.erb
<!DOCTYPE html>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
  <div class="col-md-12">

<p id="notice"><%= notice %></p>

<h2>
  <%= @score.tittle %> - <%= @score.user.name %>
</h2>

<h3>
  Key = <%= @score.key %>
</h3>

<div class="col-md-6">
  <h3>Chord</h3>
      <%= simple_format(@score.chord) %>
</div>

<div class="col-md-6">
  <h3>Degree</h3>

   <!-- ifで12x2メジャーマイナーキーの分岐,ディグリーに変換
        現在　メジャーダイアトニックのみ対応
        *マイナーキーのbの位置に注意
        例:Cナチュラルマイナーの Eb は bIII
    -->

  <% if @score.key == "C" %>
  <%= @score.chord
      hash = {'C'=>'I','C#'=>'#I','Db'=>'bII','D'=>'II','D#'=>'#II','Eb'=>'bIII','E'=>'III','F'=>'IV','F#'=>'#IV','Gb'=>'bV','G'=>'V','G#'=>'#V','Ab'=>'bVI','A'=>'VI','A#'=>'#VI','Bb'=>'bVII','B'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>

  <% elsif @score.key == "C#/Db" %>
  <%= @score.chord
      hash = {'C'=>'bI','C#'=>'I','Db'=>'I','D'=>'bII','D#'=>'II','Eb'=>'II','E'=>'#II','F'=>'III','F#'=>'IV','Gb'=>'IV','G'=>'#IV','G#'=>'V','Ab'=>'V','A'=>'bVI','A#'=>'VI','Bb'=>'VI','B'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "D" %>
  <%= @score.chord
      hash = {'D'=>'I','E'=>'II','F#'=>'III','G'=>'IV','A'=>'V','B'=>'VI','C#'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "D#/Eb" %>
  <%= @score.chord
      hash = {'Eb'=>'I','F'=>'II','G'=>'III','Ab'=>'IV','Bb'=>'V','C'=>'VI','D'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "E" %>
  <%= @score.chord
      hash = {'E'=>'I','F#'=>'II','G#'=>'III','A'=>'IV','B'=>'V','C#'=>'VI','D#'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "F" %>
  <%= @score.chord
      hash = {'F'=>'I','G'=>'II','A'=>'III','Bb'=>'IV','C'=>'V','D'=>'VI','E'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "F#/Gb" %>
  <!-- VIIの　E#(F) の表記  あとで質問 -->
  <%= @score.chord
      hash = {'F#'=>'I','G#'=>'II','A#'=>'III','Bb'=>'III','B'=>'IV','C#'=>'V','D#'=>'VI','E#'=>'VII','F'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|E#|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "G" %>
  <%= @score.chord
      hash = {'G'=>'I','A'=>'II','B'=>'III','C'=>'IV','D'=>'V','E'=>'VI','F#'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "G#/Ab" %>
  <%= @score.chord
      hash = {'G'=>'I','A'=>'II','B'=>'III','C'=>'IV','D'=>'V','E'=>'VI','F#'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "A" %>
  <%= @score.chord
      hash = {'A'=>'I','A#'=>'#I','B'=>'II','C#'=>'III','D'=>'IV','E'=>'V','F#'=>'VI','G#'=>'VII',}
      simple_format(@score.chord.gsub(/C#|Db|D|D#|Eb|E|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "A#/Bb" %>
  <%= @score.chord
      hash = {'Bb'=>'I','C'=>'II','D'=>'III','Eb'=>'IV','F'=>'V','G'=>'VI','A'=>'VII',}
      simple_format(@score.chord.gsub(/C|C#|Db|D|D#|Eb|E|F|F#|Gb|G|G#|Ab|A|A#|Bb|B|/,hash))
  %>
  <% elsif @score.key == "B" %>
  <%= @score.chord
      hash = {'B'=>'I','C#'=>'II','D#'=>'III','E'=>'IV','F#'=>'V','G#'=>'VI','A#'=>'VII',}
      simple_format(@score.chord.gsub(/C#|Db|D#|Eb|E|F#|Gb|G#|Ab|A#|Bb|B|/,hash))
  %>

  <% else %>
  <p>未実装</p>
  <% end %>
</div>

<div>
  <% if @score.user == current_user %>
  <%= link_to 'Edit', edit_score_path(@score),class: 'btn btn-info' %>
  <%= link_to 'Destroy', score_path(@score), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>
  <%= link_to 'Back', scores_path, class: 'btn btn-default' %>

</div>

</div>
</div>
</div>

app/views/top/index.html.erb
<%= render 'layouts/header' %>
<body>

<div class="jumbotron">
   <div class="container">
     <h1>Analy</h1>
     <p>Easy to chord progression analyse</p>
     <a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">Learn more »</a>
   </div>
 </div>
</body>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid masonry-container">
  <div class="row">
    <div class="col-md-8 col-sm-offset-2">
      <div class="masonry-wrapper-cols">
        <%= @user %>


      </div>
    </div>
  </div>
</div>